-- 1. Bảng Profiles: Lưu thông tin người dùng công khai
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email TEXT,
    full_name TEXT,
    avatar_url TEXT,
    banner_url TEXT,
    is_vip BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Trigger: Tự động tạo profile khi có người đăng ký mới
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, avatar_url)
  VALUES (
    new.id, 
    new.email, 
    new.raw_user_meta_data->>'full_name', 
    new.raw_user_meta_data->>'avatar_url'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 2. Bảng Phim (Movies)
CREATE TABLE IF NOT EXISTS public.movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE, 
    name TEXT NOT NULL,
    origin_name TEXT,
    poster_url TEXT,
    thumb_url TEXT,
    year INT,
    time TEXT,
    episode_current TEXT,
    episode_total TEXT,
    quality TEXT DEFAULT 'HD',
    lang TEXT,
    notify TEXT,
    showtimes TEXT,
    type TEXT,
    status TEXT,
    content TEXT,
    trailer_url TEXT,
    view INT DEFAULT 0,
    imdb_id TEXT,
    is_copyright BOOLEAN DEFAULT FALSE,
    sub_docquyen BOOLEAN DEFAULT FALSE,
    chieurap BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Bảng Thể loại (Genres)
CREATE TABLE IF NOT EXISTS public.genres (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE, 
    slug TEXT
);

-- 4. Bảng Quốc gia (Countries)
CREATE TABLE IF NOT EXISTS public.countries (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE, 
    slug TEXT
);

-- 5. Bảng Trung gian Phim - Thể loại (Many-to-Many)
CREATE TABLE IF NOT EXISTS public.movie_genres (
    movie_id BIGINT REFERENCES public.movies(id) ON DELETE CASCADE,
    genre_id INT REFERENCES public.genres(id) ON DELETE CASCADE,
    PRIMARY KEY (movie_id, genre_id)
);

-- 6. Bảng Trung gian Phim - Quốc gia (Many-to-Many)
CREATE TABLE IF NOT EXISTS public.movie_countries (
    movie_id BIGINT REFERENCES public.movies(id) ON DELETE CASCADE,
    country_id INT REFERENCES public.countries(id) ON DELETE CASCADE,
    PRIMARY KEY (movie_id, country_id)
);

-- 6.1 Bảng Tập phim (Episodes)
CREATE TABLE IF NOT EXISTS public.episodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id BIGINT REFERENCES public.movies(id) ON DELETE CASCADE,
    server_name TEXT,
    name TEXT,
    slug TEXT,
    filename TEXT,
    link_embed TEXT,
    link_m3u8 TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6.2 Bảng Diễn viên (Actors)
CREATE TABLE IF NOT EXISTS public.actors (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    slug TEXT
);

-- 6.3 Bảng Đạo diễn (Directors)
CREATE TABLE IF NOT EXISTS public.directors (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    slug TEXT
);

-- 6.4 Bảng Trung gian Phim - Diễn viên
CREATE TABLE IF NOT EXISTS public.movie_actors (
    movie_id BIGINT REFERENCES public.movies(id) ON DELETE CASCADE,
    actor_id INT REFERENCES public.actors(id) ON DELETE CASCADE,
    PRIMARY KEY (movie_id, actor_id)
);

-- 6.5 Bảng Trung gian Phim - Đạo diễn
CREATE TABLE IF NOT EXISTS public.movie_directors (
    movie_id BIGINT REFERENCES public.movies(id) ON DELETE CASCADE,
    director_id INT REFERENCES public.directors(id) ON DELETE CASCADE,
    PRIMARY KEY (movie_id, director_id)
);

-- 6.6 Bảng Thông tin TMDB (TMDB Infos)
CREATE TABLE IF NOT EXISTS public.tmdb_infos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id BIGINT REFERENCES public.movies(id) ON DELETE CASCADE UNIQUE,
    tmdb_id TEXT,
    type TEXT,
    season INT,
    vote_average NUMERIC,
    vote_count INT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Kho phim yêu thích (Library/Saved)
CREATE TABLE IF NOT EXISTS public.library (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    movie_id BIGINT NOT NULL REFERENCES public.movies(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, movie_id) 
);

-- 8. Lịch sử xem (History)
CREATE TABLE IF NOT EXISTS public.watch_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    movie_id BIGINT NOT NULL REFERENCES public.movies(id) ON DELETE CASCADE,
    episode_name TEXT, 
    last_position INT DEFAULT 0, 
    watched_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, movie_id)
);

-- Bật RLS (Bảo mật)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE library ENABLE ROW LEVEL SECURITY;
ALTER TABLE watch_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE movies ENABLE ROW LEVEL SECURITY;
ALTER TABLE genres ENABLE ROW LEVEL SECURITY;
ALTER TABLE countries ENABLE ROW LEVEL SECURITY;
ALTER TABLE movie_genres ENABLE ROW LEVEL SECURITY;
ALTER TABLE movie_countries ENABLE ROW LEVEL SECURITY;
ALTER TABLE episodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE actors ENABLE ROW LEVEL SECURITY;
ALTER TABLE directors ENABLE ROW LEVEL SECURITY;
ALTER TABLE movie_actors ENABLE ROW LEVEL SECURITY;
ALTER TABLE movie_directors ENABLE ROW LEVEL SECURITY;
ALTER TABLE tmdb_infos ENABLE ROW LEVEL SECURITY;

-- Chính sách
DO $$
DECLARE
    v_policy_exists BOOLEAN;
BEGIN
    -- 1. Users can view own profile
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'profiles' AND policyname = 'Users can view own profile') THEN
        EXECUTE 'CREATE POLICY "Users can view own profile" ON profiles FOR SELECT USING (auth.uid() = id)';
    END IF;
    
    -- 2. Users can view own library
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'library' AND policyname = 'Users can view own library') THEN
        EXECUTE 'CREATE POLICY "Users can view own library" ON library FOR SELECT USING (auth.uid() = user_id)';
    END IF;

    -- 3. Users can modify own library
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'library' AND policyname = 'Users can modify own library') THEN
        EXECUTE 'CREATE POLICY "Users can modify own library" ON library FOR ALL USING (auth.uid() = user_id)';
    END IF;

    -- 4. Users can view own history
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'watch_history' AND policyname = 'Users can view own history') THEN
        EXECUTE 'CREATE POLICY "Users can view own history" ON watch_history FOR SELECT USING (auth.uid() = user_id)';
    END IF;

    -- 5. Users can modify own history
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'watch_history' AND policyname = 'Users can modify own history') THEN
        EXECUTE 'CREATE POLICY "Users can modify own history" ON watch_history FOR ALL USING (auth.uid() = user_id)';
    END IF;

    -- 6. Public can view movies
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'movies' AND policyname = 'Public can view movies') THEN
        EXECUTE 'CREATE POLICY "Public can view movies" ON movies FOR SELECT TO authenticated, anon USING (true)';
    END IF;

    -- 7. Public can view genres
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'genres' AND policyname = 'Public can view genres') THEN
        EXECUTE 'CREATE POLICY "Public can view genres" ON genres FOR SELECT TO authenticated, anon USING (true)';
    END IF;

    -- 8. Public can view countries
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'countries' AND policyname = 'Public can view countries') THEN
        EXECUTE 'CREATE POLICY "Public can view countries" ON countries FOR SELECT TO authenticated, anon USING (true)';
    END IF;

    -- 9. Public can view movie genres
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'movie_genres' AND policyname = 'Public can view movie genres') THEN
        EXECUTE 'CREATE POLICY "Public can view movie genres" ON movie_genres FOR SELECT TO authenticated, anon USING (true)';
    END IF;

    -- 10. Public can view movie countries
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'movie_countries' AND policyname = 'Public can view movie countries') THEN
        EXECUTE 'CREATE POLICY "Public can view movie countries" ON movie_countries FOR SELECT TO authenticated, anon USING (true)';
    END IF;

    -- 11. Public can view episodes
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'episodes' AND policyname = 'Public can view episodes') THEN
        EXECUTE 'CREATE POLICY "Public can view episodes" ON episodes FOR SELECT TO authenticated, anon USING (true)';
    END IF;

    -- 12. Public can view actors
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'actors' AND policyname = 'Public can view actors') THEN
        EXECUTE 'CREATE POLICY "Public can view actors" ON actors FOR SELECT TO authenticated, anon USING (true)';
    END IF;

    -- 13. Public can view directors
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'directors' AND policyname = 'Public can view directors') THEN
        EXECUTE 'CREATE POLICY "Public can view directors" ON directors FOR SELECT TO authenticated, anon USING (true)';
    END IF;

    -- 14. Public can view movie actors
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'movie_actors' AND policyname = 'Public can view movie actors') THEN
        EXECUTE 'CREATE POLICY "Public can view movie actors" ON movie_actors FOR SELECT TO authenticated, anon USING (true)';
    END IF;

    -- 15. Public can view movie directors
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'movie_directors' AND policyname = 'Public can view movie directors') THEN
        EXECUTE 'CREATE POLICY "Public can view movie directors" ON movie_directors FOR SELECT TO authenticated, anon USING (true)';
    END IF;

    -- 16. Public can view tmdb_infos
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'tmdb_infos' AND policyname = 'Public can view tmdb_infos') THEN
        EXECUTE 'CREATE POLICY "Public can view tmdb_infos" ON tmdb_infos FOR SELECT TO authenticated, anon USING (true)';
    END IF;

    RAISE NOTICE 'All RLS policies have been created successfully';
END
$$;

-- Function: Sync Movie Data
CREATE OR REPLACE FUNCTION public.sync_movie_data(
    p_movie_data JSONB
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER 
AS $$
DECLARE
    v_movie_id BIGINT;
    v_item JSONB;
    v_server JSONB;
    v_episode JSONB;
    v_sub_id INT;
BEGIN
    -- 1. Insert hoặc Update bảng Movies
    INSERT INTO public.movies (
        slug, name, origin_name, poster_url, thumb_url, year, type, lang, time, quality, 
        episode_current, episode_total, notify, showtimes, status, content, trailer_url,
        view, imdb_id,
        is_copyright, sub_docquyen, chieurap, updated_at
    )
    VALUES (
        p_movie_data->'movie'->>'slug',
        p_movie_data->'movie'->>'name',
        p_movie_data->'movie'->>'origin_name',
        p_movie_data->'movie'->>'poster_url',
        p_movie_data->'movie'->>'thumb_url',
        (p_movie_data->'movie'->>'year')::INT,
        p_movie_data->'movie'->>'type',
        p_movie_data->'movie'->>'lang',
        p_movie_data->'movie'->>'time',
        p_movie_data->'movie'->>'quality',
        p_movie_data->'movie'->>'episode_current',
        p_movie_data->'movie'->>'episode_total',
        p_movie_data->'movie'->>'notify',
        p_movie_data->'movie'->>'showtimes',
        p_movie_data->'movie'->>'status',
        p_movie_data->'movie'->>'content',
        p_movie_data->'movie'->>'trailer_url',
        (p_movie_data->'movie'->>'view')::INT,
        p_movie_data->'movie'->'imdb'->>'id',
        (p_movie_data->'movie'->>'is_copyright')::BOOLEAN,
        (p_movie_data->'movie'->>'sub_docquyen')::BOOLEAN,
        (p_movie_data->'movie'->>'chieurap')::BOOLEAN,
        NOW()
    )
    ON CONFLICT (slug) DO UPDATE SET
        name = EXCLUDED.name,
        origin_name = EXCLUDED.origin_name,
        poster_url = EXCLUDED.poster_url,
        thumb_url = EXCLUDED.thumb_url,
        year = EXCLUDED.year,
        type = EXCLUDED.type,
        lang = EXCLUDED.lang,
        time = EXCLUDED.time,
        quality = EXCLUDED.quality,
        episode_current = EXCLUDED.episode_current,
        episode_total = EXCLUDED.episode_total,
        notify = EXCLUDED.notify,
        showtimes = EXCLUDED.showtimes,
        status = EXCLUDED.status,
        content = EXCLUDED.content,
        trailer_url = EXCLUDED.trailer_url,
        view = EXCLUDED.view,
        imdb_id = EXCLUDED.imdb_id,
        is_copyright = EXCLUDED.is_copyright,
        sub_docquyen = EXCLUDED.sub_docquyen,
        chieurap = EXCLUDED.chieurap,
        updated_at = NOW()
    RETURNING id INTO v_movie_id;

    -- 1.1 Insert/Update TMDB Infos
    IF p_movie_data->'movie'->'tmdb' IS NOT NULL THEN
        INSERT INTO public.tmdb_infos (
            movie_id, tmdb_id, type, season, vote_average, vote_count, updated_at
        )
        VALUES (
            v_movie_id,
            p_movie_data->'movie'->'tmdb'->>'id',
            p_movie_data->'movie'->'tmdb'->>'type',
            (p_movie_data->'movie'->'tmdb'->>'season')::INT,
            (p_movie_data->'movie'->'tmdb'->>'vote_average')::NUMERIC,
            (p_movie_data->'movie'->'tmdb'->>'vote_count')::INT,
            NOW()
        )
        ON CONFLICT (movie_id) DO UPDATE SET
            tmdb_id = EXCLUDED.tmdb_id,
            type = EXCLUDED.type,
            season = EXCLUDED.season,
            vote_average = EXCLUDED.vote_average,
            vote_count = EXCLUDED.vote_count,
            updated_at = NOW();
    END IF;

    -- 2. Xử lý Thể loại (Genres)
    IF p_movie_data->'movie'->'category' IS NOT NULL THEN
        FOR v_item IN SELECT * FROM jsonb_array_elements(p_movie_data->'movie'->'category')
        LOOP
            INSERT INTO public.genres (name, slug)
            VALUES (v_item->>'name', v_item->>'slug')
            ON CONFLICT (name) DO UPDATE SET slug = EXCLUDED.slug
            RETURNING id INTO v_sub_id;

            INSERT INTO public.movie_genres (movie_id, genre_id)
            VALUES (v_movie_id, v_sub_id)
            ON CONFLICT DO NOTHING;
        END LOOP;
    END IF;

    -- 3. Xử lý Quốc gia (Countries)
    IF p_movie_data->'movie'->'country' IS NOT NULL THEN
        FOR v_item IN SELECT * FROM jsonb_array_elements(p_movie_data->'movie'->'country')
        LOOP
            INSERT INTO public.countries (name, slug)
            VALUES (v_item->>'name', v_item->>'slug')
            ON CONFLICT (name) DO UPDATE SET slug = EXCLUDED.slug
            RETURNING id INTO v_sub_id;

            INSERT INTO public.movie_countries (movie_id, country_id)
            VALUES (v_movie_id, v_sub_id)
            ON CONFLICT DO NOTHING;
        END LOOP;
    END IF;

    -- 4. Xử lý Diễn viên (Actors)
    IF p_movie_data->'movie'->'actor' IS NOT NULL AND jsonb_typeof(p_movie_data->'movie'->'actor') = 'array' THEN
        FOR v_item IN SELECT * FROM jsonb_array_elements(p_movie_data->'movie'->'actor')
        LOOP
            -- Actor name only in JSON array ["Name 1", "Name 2"]
            INSERT INTO public.actors (name)
            VALUES (TRIM(BOTH '"' FROM v_item::text))
            ON CONFLICT (name) DO NOTHING
            RETURNING id INTO v_sub_id;
            
            -- If ID not returned (due to conflict), fetch it
            IF v_sub_id IS NULL THEN
                SELECT id INTO v_sub_id FROM public.actors WHERE name = TRIM(BOTH '"' FROM v_item::text);
            END IF;

            INSERT INTO public.movie_actors (movie_id, actor_id)
            VALUES (v_movie_id, v_sub_id)
            ON CONFLICT DO NOTHING;
        END LOOP;
    END IF;

    -- 5. Xử lý Đạo diễn (Directors)
    IF p_movie_data->'movie'->'director' IS NOT NULL AND jsonb_typeof(p_movie_data->'movie'->'director') = 'array' THEN
        FOR v_item IN SELECT * FROM jsonb_array_elements(p_movie_data->'movie'->'director')
        LOOP
            INSERT INTO public.directors (name)
            VALUES (TRIM(BOTH '"' FROM v_item::text))
            ON CONFLICT (name) DO NOTHING
            RETURNING id INTO v_sub_id;

            IF v_sub_id IS NULL THEN
                 SELECT id INTO v_sub_id FROM public.directors WHERE name = TRIM(BOTH '"' FROM v_item::text);
            END IF;

            INSERT INTO public.movie_directors (movie_id, director_id)
            VALUES (v_movie_id, v_sub_id)
            ON CONFLICT DO NOTHING;
        END LOOP;
    END IF;

    -- 6. Xử lý Tập phim (Episodes)
    -- Xóa tập cũ để cập nhật mới (hoặc có thể dùng upsert thông minh hơn nếu cần)
    -- Ở đây chọn xóa cũ phim này đi insert lại cho đơn giản và đảm bảo sync đúng list mới nhất
    DELETE FROM public.episodes WHERE movie_id = v_movie_id;

    IF p_movie_data->'episodes' IS NOT NULL THEN
        FOR v_server IN SELECT * FROM jsonb_array_elements(p_movie_data->'episodes')
        LOOP
            IF v_server->'server_data' IS NOT NULL THEN
                FOR v_episode IN SELECT * FROM jsonb_array_elements(v_server->'server_data')
                LOOP
                    INSERT INTO public.episodes (
                        movie_id, server_name, name, slug, filename, link_embed, link_m3u8
                    )
                    VALUES (
                        v_movie_id,
                        v_server->>'server_name',
                        v_episode->>'name',
                        v_episode->>'slug',
                        v_episode->>'filename',
                        v_episode->>'link_embed',
                        v_episode->>'link_m3u8'
                    );
                END LOOP;
            END IF;
        END LOOP;
    END IF;

    RETURN v_movie_id;
END;
$$;
